CREATE TABLE DEPOSIT(
ACTNO INT,
CNAME VARCHAR(50),
BNAME VARCHAR(50),
AMOUNT DECIMAL(8,2),
ADATE DATETIME)

INSERT INTO DEPOSIT VALUES
(109,'MINU','POWAI',7000,1995-8-10);

SELECT * FROM DEPOSIT

CREATE TABLE BRANCH(
BNAME VARCHAR(50),
CITY VARCHAR(50))

INSERT INTO BRANCH VALUES
('VRCE','NAGPUR'),
('AJNI','NAGPUR'),
('KAROLBAGH','DELHI'),
('CHANDI','DELHI'),
('DHARAMPETH','NAGPUR'),
('M.G.ROAD','BANGLORE'),
('ANDHERI','BOMBAY'),
('VIRAR','BOMBAY'),
('NEHRU PLACE','DELHI'),
('POWAI','BOMBAY');

SELECT * FROM BRANCH

CREATE TABLE CUSTOMERS(
CNAME VARCHAR(50),
CITY VARCHAR(50))

INSERT INTO CUSTOMERS VALUES
('NAREN','BOMBAY');

SELECT * FROM CUSTOMERS

SELECT * FROM BORROW