CREATE DATABASE  CSE_3B_310

CREATE TABLE SALESW_DATA
(
REGION VARCHAR(50),
PRODUCT VARCHAR(50),
SALES_AMOUNT INT,
YEAR INT
)

INSERT INTO SALESW_DATA(REGION,PRODUCT,SALES_AMOUNT,YEAR)
VALUES
('NORTH AMERICA','WATCH',1500,2023),
('EUROPE','MOBILE',1200,2023),
('ASIA','WATCH',1800,2023),
('NORTH AMERICA','TV',900,2024),
('EUROPE','WATCH',2000,2024),
('ASIA','MOBILE',1000,2024),
('NORTH AMERICA','MOBILE',1600,2023),
('EUROPE','TV',1500,2023),
('ASIA','TV',1100,2024),
('NORTH AMERICA','WATCH',1700,2024)

SELECT * FROM SALESW_DATA
DROP TABLE SALESW_DATA



-------------------------------------------PART A--------------------------------------------------

--1.Display Total Sales Amount by Region
SELECT SUM(SALES_AMOUNT) AS TOTAL_SALARY,REGION
FROM SALESW_DATA
GROUP BY REGION

--2.Display Average Sales Amount by Product.SELECT AVG(SALES_AMOUNT) AS AVERAGE,PRODUCTFROM SALESW_DATAGROUP BY PRODUCT--3.Display Maximum Sales Amount by Year.SELECT MAX(SALES_AMOUNT) AS MAXIMUM,YEARFROM SALESW_DATAGROUP BY YEAR--4.Display Minimum Sales Amount by Region and Year.SELECT MIN(SALES_AMOUNT),REGION,YEAR AS MIN_SALESFROM SALESW_DATAGROUP BY REGION,YEAR --5.Count of Products Sold by Region.SELECT COUNT(PRODUCT),REGION AS TOTAL_PRODUCTFROM SALESW_DATAGROUP BY REGION--6.. Display Sales Amount by Year and Product.SELECT SUM(SALES_AMOUNT),YEAR,PRODUCT AS TOTAL_AMOUNFROM SALESW_DATAGROUP BY YEAR,PRODUCT--7.Display Regions with Total Sales Greater Than 5000.SELECT SUM(SALES_AMOUNT),REGION AS TOTAL_AMOUNTFROM SALESW_DATAGROUP BY REGIONHAVING SUM(SALES_AMOUNT)>5000--8.Display Products with Average Sales Less Than 10000.SELECT AVG(SALES_AMOUNT),PRODUCT AS AVG_AMOUNTFROM SALESW_DATAGROUP BY PRODUCTHAVING AVG(SALES_AMOUNT)<10000--9.. Display Years with Maximum Sales Exceeding 500.SELECT MAX(SALES_AMOUNT) ,YEAR AS MAX_AMOUNTFROM SALESW_DATAGROUP BY YEARHAVING  MAX(SALES_AMOUNT)>500--10.Display Regions with at Least 3 Distinct Products Sold.SELECT COUNT( PRODUCT) ,REGIONFROM SALESW_DATAGROUP BY REGIONHAVING COUNT(DISTINCT PRODUCT) >=3--11.. Display Years with Minimum Sales Less Than 1000.SELECT MIN(SALES_AMOUNT) ,YEAR AS YEARFROM SALESW_DATAGROUP BY YEARHAVING MIN(SALES_AMOUNT)<1000--12. Display Total Sales Amount by Region for Year 2023, Sorted by Total Amount.SELECT SUM(SALES_AMOUNT),REGIONFROM SALESW_DATAWHERE YEAR=2023GROUP BY REGIONORDER BY SUM(SALES_AMOUNT)------------------------------------------------PART B----------------------------------------------------------1.Display Count of Orders by Year and Region, Sorted by Year and Region.SELECT COUNT(YEAR),YEAR,REGION AS TOTAL_YEARFROM SALESW_DATAGROUP BY YEAR,REGIONORDER BY YEAR,REGION--2.Display Regions with Maximum Sales Amount Exceeding 1000 in Any Year, Sorted by Region.SELECT MAX(SALES_AMOUNT) ,REGION AS MAX_AMOUNTFROM SALESW_DATAGROUP BY REGIONHAVING  MAX(SALES_AMOUNT)>1000ORDER BY REGION--3.Display Years with Total Sales Amount Less Than 1000, Sorted by Year Descending.SELECT SUM(SALES_AMOUNT) ,YEARFROM SALESW_DATAGROUP BY YEARHAVING SUM(SALES_AMOUNT)<1000ORDER BY YEAR DESC--4.Display Top 3 Regions by Total Sales Amount in Year 2024.SELECT TOP 3 REGION, SUM(SALES_AMOUNT)FROM SALESW_DATAWHERE YEAR=2024GROUP BY REGION-----------------------------------------PART C------------------------------------------------1.Display Products with Average Sales Amount Between 1000 and 2000, Ordered by Product Name.SELECT AVG(SALES_AMOUNT),PRODUCTFROM SALESW_DATAGROUP BY PRODUCTHAVING AVG(SALES_AMOUNT) BETWEEN 1000 AND 2000ORDER BY PRODUCT--2.Display Years with More Than 5 Orders from Each Region.SELECT COUNT( PRODUCT),YEARFROM SALESW_DATAGROUP BY YEARHAVING COUNT(PRODUCT)>5---3.Display Regions with Average Sales Amount Above 1500 in Year 2023 sort by amount in descending.SELECT AVG(SALES_AMOUNT),REGIONFROM SALESW_DATAWHERE YEAR=2023GROUP BY REGIONHAVING AVG(SALES_AMOUNT)>1500ORDER BY AVG(SALES_AMOUNT) DESC--4.. Find out region wise duplicate product.SELECT COUNT(PRODUCT),REGION,PRODUCTFROM SALESW_DATAGROUP BY REGION,PRODUCTHAVING COUNT(PRODUCT)>=2--5.Find out region wise highest sales amount.SELECT MAX(SALES_AMOUNT),REGIONFROM SALESW_DATAGROUP BY REGION